  spring:
    application:
      name: meetingroom

    datasource:
      url: jdbc:mysql://localhost:3309/meeting_room_db
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      open-in-view: false
      properties:
        hibernate:
          format_sql: true

    jackson:
      time-zone: Asia/Jakarta

  server:
    port: 9000

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
